language: node_js
node_js:
  - 0.10
  - 0.8

notifications:
  email:
    recipients:
      - eric@sunlightfoundation.com
      - tneale@sunlightfoundation.com
    on_success: change
    on_failure: change