language: node_js
node_js:
  - 0.10

notifications:
  email:
    recipients:
      - eric@konklone.com
      - tneale@sunlightfoundation.com
      - adelevie@gmail.com
    on_success: change
    on_failure: change

branches:
  only:
    - master